services:
  postgres:
    container_name: mindswap-mysql
    image: mysql:latest
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 123456
    volumes:
      - /var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - mysql
    restart: unless-stopped

networks:
  postgres:
    driver: bridge

volumes:
  postgres: